# Generated by Django 3.2.7 on 2021-12-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='owner',
            new_name='author',
        ),
    ]
